# Generated by Django 3.1.2 on 2021-11-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iraq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numvolunteer',
            name='n_intity',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
