# Generated by Django 3.1.2 on 2021-11-26 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iraq', '0002_numvolunteer_n_intity'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iraq.customuser'),
            preserve_default=False,
        ),
    ]
